server:
  port: ${PORT:8080}
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: 35000
  application:
    name: tunnel-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: itpusr
    password: itp@168
    url: jdbc:postgresql://localhost:5168/itp_main_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    session:
      timeout: 30m

# ✅ Tunnel domain config
tunnel:
  domain: 192.168.43.219.nip.io   # ← Free wildcard DNS

app:
  auth:
    mock-enabled: true
  iam:
    base-url: http://localhost:9090

axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.AccountCQRS.Events
    client-id: kafka-axon-account
    message-converter-mode: default
    properties:
      security.protocol: PLAINTEXT
    publisher:
      confirmation-mode: transactional
    producer:
      transaction-id-prefix: kafka-axon-
      retries: 5
      event-processor-mode: tracking
  serializer:
    general: jackson
    events: jackson
    messages: jackson

logging:
  level:
    root: INFO
    com.istad.stadoor: DEBUG
    org.springframework.web.socket: DEBUG