#version: "3.9"
#
#services:
#  postgres:
#    image: postgres:16
#    container_name: stadoor-postgres
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: tunnel_db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - stadoor_postgres_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d tunnel_db"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#volumes:
#  stadoor_postgres_data:
